version: 0.2

phases:
  install:
    commands:


      - apt-get update
      - wget -O- https://apt.corretto.aws/corretto.key |  apt-key add -
      - echo 'deb https://apt.corretto.aws stable main' |  tee /etc/apt/sources.list.d/corretto.list
      - apt-get update
      - apt-get install java-16-amazon-corretto-jdk



  pre_build:
    commands:
      - chmod 777 gradlew
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
#    - scripts/*.sh
#    - appspec.yml
  #com/mycompany/app/HelloWorld.java, specifying yes will place this file in /HelloWorld.java
  discard-paths: yes


