version: 0.2

phases:
  install:
    commands:

      - wget https://corretto.aws/downloads/latest/amazon-corretto-16-x64-linux-jdk.deb
      - apt-get update &&  apt-get install java-common
      - dpkg --install amazon-corretto-16-x64-linux-jdk.d
      - java -version

  pre_build:
    commands:
      - chmod 777 gradlew
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
#    - scripts/*.sh
#    - appspec.yml
  #com/mycompany/app/HelloWorld.java, specifying yes will place this file in /HelloWorld.java
  discard-paths: yes


